services:
  mongodb:
    image: mongodb:v1


networks:
   defaults:
     driver: bridge 
     name: roboshop
     external: false # true if you have created network manually using network network command 
     